# -*- coding: utf-8 -*-
"""data_household.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P27jHLkYm6p2N2HS0Vn4ubQDyv0R9taD
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

from google.colab import drive
drive.mount('/content/drive')

def break_datetime(df):
    df['utc_timestamp']= pd.to_datetime(df['utc_timestamp'])
    df[['year','weekofyear','dayofweek']]= np.uint16(df['utc_timestamp'].dt.isocalendar())
    df['month']= np.uint8(df['utc_timestamp'].dt.month)
    df['hour']= np.uint8(df['utc_timestamp'].dt.hour)
    return df

df2 = pd.read_csv('/content/drive/My Drive/household_data_60min_singleindex.csv')
print(df2.head(20))

df_consumption = df2.copy()
df_consumption = df_consumption.loc[:, ~df_consumption.columns.str.contains('charge|decharge|pv', case=False)]

df_consumption.head(20)

df_consumption['utc_timestamp'] = pd.to_datetime(df_consumption['utc_timestamp'])
df_consumption['utc_timestamp'] = df_consumption['utc_timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')
df_consumption = break_datetime(df_consumption)

"""#DF_REF"""

drive_path = '/content/drive/My Drive/'  # Adjust this path as needed

file_path1 = os.path.join(drive_path, 'df_ref.csv')

df_ref = df_consumption.copy()
df_ref = df_ref.loc[:, df_ref.columns.str.contains('refrigerator|timestamp', case=False, regex=True)]
df_ref = break_datetime(df_ref)
df_ref.to_csv(file_path1, index=False)
df_ref.head(20)

#df_ref['timestamp'] = pd.to_datetime(df_ref['utc_timestamp'])
ref_columns = [col for col in df_ref.columns if 'refrigerator' in col.lower()]


# Plot dishwasher consumption throughout the day
plt.figure(figsize=(12, 6))
for col in ref_columns:
    plt.plot(df_ref['utc_timestamp'], df_ref[col], label=col)

plt.xlabel('Timestamp')
plt.ylabel('Consumption(kWh)')
plt.title('Refrigerator Consumption Throughout The Time')
plt.legend()
plt.grid(True)
plt.show()

df_ref.head()

"""#DF_HEAT"""

df_heat = df_consumption.copy()
df_heat = df_heat.loc[:, df_heat.columns.str.contains('heat|timestamp',case=False, regex=True)]

file_path3 = os.path.join(drive_path, 'df_heat.csv')

df_heat = break_datetime(df_heat)
df_heat.to_csv(file_path3, index=False)

df_heat.head(20)

"""#DF_DISHWASH"""

df_dishwash = df_consumption.copy()
df_dishwash = df_dishwash.loc[:, df_dishwash.columns.str.contains('dishwasher|timestamp',case=False, regex=True)]

file_path2 = os.path.join(drive_path, 'df_dishwash.csv')

df_dishwash = break_datetime(df_dishwash)
df_dishwash.to_csv(file_path2, index=False)

df_dishwash.head(20)

df_dishwash.hist(bins=15, figsize = (10,8))

df_dishwash.info()

df_dishwash.describe()

df_dishwash.plot()

df_dishwash['timestamp'] = pd.to_datetime(df_dishwash['utc_timestamp'])
dishwasher_columns = [col for col in df_dishwash.columns if 'dishwasher' in col.lower()]


# Plot dishwasher consumption throughout the day
plt.figure(figsize=(12, 6))
for col in dishwasher_columns:
    plt.plot(df_dishwash['timestamp'], df_dishwash[col], label=col)

plt.xlabel('Timestamp')
plt.ylabel('Consumption(kWh)')
plt.title('Dishwasher Consumption Throughout The Time')
plt.legend()
plt.grid(True)
plt.show()