# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rr1FSkL9x2rEGugwJEUY8PXOHdFiUlSA
"""

import pandas as pd
import numpy as np
#import joblib
#import zipfile
#import os
import holidays

def break_datetime(df):
    df['utc_timestamp']= pd.to_datetime(df['utc_timestamp'])
    df[['year','weekofyear','dayofweek']]= np.uint16(df['utc_timestamp'].dt.isocalendar())
    df['month']= np.uint8(df['utc_timestamp'].dt.month)
    df['hour']= np.uint8(df['utc_timestamp'].dt.hour)
    return df

def circular_encode(df, feature, max_value):
    df[feature+'_sin'] = np.sin(2 * np.pi * df[feature] / max_value)
    df[feature+'_cos']  = np.cos(2 * np.pi * df[feature] / max_value)
    return df

def apply_holidays(df):
    # Load holiday data for England
    england_holidays = holidays.UnitedKingdom(years=range(2016, 2017))

    # Load holiday data for the United States
    us_holidays = holidays.UnitedStates(years=range(2016, 2017))

    # Initialize 'is_holiday' column with zeros
    df['is_holiday'] = 0

    # Create 'is_holiday_england' feature
    england_mask = df['site_id'] == 1
    df.loc[england_mask, 'is_holiday'] = df.loc[england_mask, 'timestamp'].apply(lambda x: 1 if x in england_holidays else 0)

    # Create 'is_holiday_us' feature
    us_mask = df['site_id'] == 6
    df.loc[us_mask, 'is_holiday'] = df.loc[us_mask, 'timestamp'].apply(lambda x: 1 if x in us_holidays else 0)

    return df